### ISSUE TITLE
Increase maximum possible price

### ISSUE THREAD

**Issue by hannahhall** [nss-evening-cohort-12/bangazon-api-nswalters#10]
The system currently will reject any product being created with a price greater than $10,000. Increase that maximum to $17,500.

**Comment by nswalters** [comment]
Update in `models/product.py`:

```python
    price = models.FloatField(
        validators=[MinValueValidator(0.00), MaxValueValidator(10000.00)],)
```

**Comment by nswalters** [comment]
This rejection actually wasn't working at all.

The validators on the model are not automatically ran unless you're using a ModelForm.  See: https://docs.djangoproject.com/en/dev/ref/validators/#how-validators-are-run

> See the form validation for more information on how validators are run in forms, and Validating objects for how they’re run in models. Note that validators will not be run automatically when you save a model, but if you are using a ModelForm, it will run your validators on any fields that are included in your form.

You need to include a call to Model.clean_fields() to run the validators if you aren't using the ModelForm. See: https://docs.djangoproject.com/en/dev/ref/models/instances/#validating-objects

Here's what I did in views/product.py:
```
new_product.clean_fields() # This is the new code
new_product.save()
```

And here's the error I got when attempting to save a new product with a value greater than 10000:
```
ValidationError at /products
{'price': ['Ensure this value is less than or equal to 10000.0.']}
```
